/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enviospractica1.UI.operador;

import enviospractica1.Backend.Destino;
import enviospractica1.Backend.Factura;
import enviospractica1.Backend.Paquete;
import enviospractica1.Backend.PuntoControl;
import enviospractica1.Backend.Usuario;
import enviospractica1.UI.IngresarUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author astridmc
 */
public class ProcesarPaquete extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProcesarPaquete
     */
    String cui;
    Usuario usuario = new Usuario();
    PuntoControl puntosControl = new PuntoControl();
    Paquete paquete = new Paquete();
    Destino destino = new Destino();
    Factura factura = new Factura();
    private int validador;
    public ProcesarPaquete() {
        validador=1;
        initComponents();
        Diseño();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombres = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNoGuia = new javax.swing.JLabel();
        panelInfoPaquete = new javax.swing.JPanel();
        txtNombre = new javax.swing.JLabel();
        lblRemitente = new javax.swing.JLabel();
        txtDestino = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblNoHoras = new javax.swing.JLabel();
        txtNoHoras = new javax.swing.JTextField();
        btnProcesar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        paquetes = new javax.swing.JComboBox<>();
        puntoControl = new javax.swing.JComboBox<>();

        lblNombres.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNombres.setText("****************************");

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(30, 65, 32));
        lblNombre.setText("Nombre del remitente :");

        jPanel1.setBackground(new java.awt.Color(141, 234, 179));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(30, 65, 32));
        lblTitulo.setText("PROCESAR PAQUETE");

        lblNoGuia.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNoGuia.setForeground(new java.awt.Color(30, 65, 32));
        lblNoGuia.setText(" No. Guia:");

        panelInfoPaquete.setBackground(new java.awt.Color(214, 251, 230));
        panelInfoPaquete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 201, 178), 2, true));

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNombre.setText("****************************");

        lblRemitente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblRemitente.setForeground(new java.awt.Color(30, 65, 32));
        lblRemitente.setText("remitente :");

        txtDestino.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtDestino.setText("****************************");

        lblDestino.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(30, 65, 32));
        lblDestino.setText("Destino :");

        javax.swing.GroupLayout panelInfoPaqueteLayout = new javax.swing.GroupLayout(panelInfoPaquete);
        panelInfoPaquete.setLayout(panelInfoPaqueteLayout);
        panelInfoPaqueteLayout.setHorizontalGroup(
            panelInfoPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDestino)
                    .addComponent(lblRemitente))
                .addGap(100, 100, 100)
                .addGroup(panelInfoPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre)
                    .addComponent(txtDestino))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        panelInfoPaqueteLayout.setVerticalGroup(
            panelInfoPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre)
                    .addComponent(lblRemitente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panelInfoPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestino)
                    .addComponent(txtDestino))
                .addGap(29, 29, 29))
        );

        lblNoHoras.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNoHoras.setForeground(new java.awt.Color(30, 65, 32));
        lblNoHoras.setText("Ingrese No. Horas de Permanencia:");

        txtNoHoras.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        txtNoHoras.setForeground(new java.awt.Color(13, 58, 12));
        txtNoHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoHorasActionPerformed(evt);
            }
        });
        txtNoHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoHorasKeyTyped(evt);
            }
        });

        btnProcesar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnProcesar.setText("PROCESAR");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        paquetes.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        paquetes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "******" }));
        paquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paquetesMouseClicked(evt);
            }
        });
        paquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paquetesActionPerformed(evt);
            }
        });

        puntoControl.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        puntoControl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "******" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelInfoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(lblNoHoras)
                            .addGap(40, 40, 40)
                            .addComponent(txtNoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblNoGuia)
                        .addGap(75, 75, 75)
                        .addComponent(paquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntoControl, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(puntoControl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoGuia)
                    .addComponent(paquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(panelInfoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoHoras)
                    .addComponent(txtNoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHorasActionPerformed

    }//GEN-LAST:event_txtNoHorasActionPerformed

    private void txtNoHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoHorasKeyTyped
        char f = evt.getKeyChar();
        if(f<'0'||f>'9') evt.consume();
    }//GEN-LAST:event_txtNoHorasKeyTyped

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        if(txtNoHoras.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"NO HA ESPECIFICADO EL NUMRO DE HORAS");
        }else{
            int precio= puntosControl.obtenerPrecioIndividual(IngresarUsuario.conector)* Integer.parseInt(txtNoHoras.getText());
            paquete.ingresarHoras(IngresarUsuario.conector, paquetes.getSelectedItem().toString(),Integer.valueOf(txtNoHoras.getText()),precio );
            JOptionPane.showMessageDialog(null,"EL PAQUETE HA SIDO PROCESADO");
            vaciarCampos();
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int idFactura = paquete.obtenerFactura(IngresarUsuario.conector, paquetes.getSelectedItem().toString());
        panelInfoPaquete.setVisible(true);
        vaciarCampos();
        int miDestino =paquete.obtenerDestino(IngresarUsuario.conector, paquetes.getSelectedItem().toString());
        txtDestino.setText(destino.obtenerNombre(IngresarUsuario.conector, miDestino));
        txtNombre.setText(factura.obtenerRemitente(IngresarUsuario.conector, idFactura));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       if(validador==1){
            cui = usuario.obtenerCui(IngresarUsuario.conector);
            System.out.println(cui);
            puntosControl.obtenerPuntoDeOperador(IngresarUsuario.conector, cui, puntoControl);
            validador=2;
       }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void paquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paquetesActionPerformed
        
    }//GEN-LAST:event_paquetesActionPerformed

    private void paquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paquetesMouseClicked
        paquete.obtenerPaquetesDelPunto(IngresarUsuario.conector, puntoControl.getSelectedItem().toString(), paquetes);
    }//GEN-LAST:event_paquetesMouseClicked

    private void Diseño(){
        panelInfoPaquete.setVisible(false);
        this.setClosable(true);
        this.setResizable(true);
        this.setIconifiable(true);
        this.setTitle("PROCESAR PAQUETE");
    }
    
    private void vaciarCampos(){
        txtDestino.setText("**************************************");
        txtNombre.setText("**************************************");
        txtNoHoras.setText("");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblNoGuia;
    private javax.swing.JLabel lblNoHoras;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblRemitente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelInfoPaquete;
    private javax.swing.JComboBox<String> paquetes;
    private javax.swing.JComboBox<String> puntoControl;
    private javax.swing.JLabel txtDestino;
    private javax.swing.JTextField txtNoHoras;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
