/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enviospractica1.UI.recepcionista;

import enviospractica1.Backend.Cliente;
import enviospractica1.UI.IngresarUsuario;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author astridmc
 */
public class RegistroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroCliente
     */
    private int verificador;
    private String nombre;
    private String apellido;
    private String nitOtenido;
    
    
    public RegistroCliente() {
        initComponents();
        Diseño();
    }
    
    public RegistroCliente(String nit) {
        initComponents();
        Diseño();
        this.nitOtenido = nit;
        txtNIT.setText(nit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtApellido1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtCUI = new javax.swing.JTextField();
        lblCUI = new javax.swing.JLabel();
        LblTitulo = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtCelular = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        lblCelular1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(139, 249, 187));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        txtApellido1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtApellido1.setForeground(new java.awt.Color(13, 58, 12));
        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(141, 234, 179));

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(30, 65, 32));
        lblNombre.setText("Ingrese Nombres :");

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(13, 58, 12));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lblApellido.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(30, 65, 32));
        lblApellido.setText("Ingrese Apellidos :");

        txtCUI.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtCUI.setForeground(new java.awt.Color(13, 58, 12));
        txtCUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCUIActionPerformed(evt);
            }
        });
        txtCUI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCUIKeyTyped(evt);
            }
        });

        lblCUI.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblCUI.setForeground(new java.awt.Color(30, 65, 32));
        lblCUI.setText("Ingrese Numero de CUI:");

        LblTitulo.setFont(new java.awt.Font("Abyssinica SIL", 1, 28)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(30, 65, 32));
        LblTitulo.setText("REGISTRO DE UN NUEVO CLIENTE");

        btnGuardar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtCelular.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(13, 58, 12));
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });

        lblCelular.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(30, 65, 32));
        lblCelular.setText("Ingrese Numero de Celular:");

        txtNIT.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtNIT.setForeground(new java.awt.Color(13, 58, 12));
        txtNIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNITActionPerformed(evt);
            }
        });
        txtNIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNITKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNITKeyPressed(evt);
            }
        });

        lblCelular1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblCelular1.setForeground(new java.awt.Color(30, 65, 32));
        lblCelular1.setText("Ingrese Numero de NIT:");

        txtApellido.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(13, 58, 12));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        lblDireccion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(30, 65, 32));
        lblDireccion.setText("Direccion:");

        txtDireccion.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(13, 58, 12));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblApellido)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(LblTitulo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 483, Short.MAX_VALUE)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCUI)
                                    .addComponent(lblCelular1)
                                    .addComponent(lblNombre)
                                    .addComponent(lblCelular, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCUI, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(LblTitulo)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblApellido)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCUI))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCUIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCUIActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        validar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        char a = evt.getKeyChar();
        if(a<'0'||a>'9') evt.consume();
        if( txtCelular.getText().length()==8) evt.consume();
    }//GEN-LAST:event_txtCelularKeyTyped

    private void txtCUIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCUIKeyTyped
        char b = evt.getKeyChar();
        if(b<'0'||b>'9') evt.consume();
        if(txtCUI.getText().length()==13) evt.consume();
    }//GEN-LAST:event_txtCUIKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a'|| c>'z') && (c<'A'||c>'z')&&(c<' '|| c>' ')) {
            evt.consume();}
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNITActionPerformed

    private void txtNITKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNITKeyTyped
        char f = evt.getKeyChar();
        if(f<'0'||f>'9') evt.consume();
        if(txtNIT.getText().length()==7) txtNIT.setText(txtNIT.getText()+"-");
        
        if(txtNIT.getText().length()==9) evt.consume();
        
    }//GEN-LAST:event_txtNITKeyTyped

    private void txtNITKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNITKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
            if(txtNIT.getText().length()>7){
                txtNIT.setText(" ");
            }
        }
    }//GEN-LAST:event_txtNITKeyPressed

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed

    }//GEN-LAST:event_txtApellido1ActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a'|| c>'z') && (c<'A'||c>'z')&&(c<' '|| c>' ')) {
            evt.consume();}
        if(txtDireccion.getText().length()==60) evt.consume();
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a'|| c>'z') && (c<'A'||c>'z')&&(c<' '|| c>' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    public void Diseño() {
        this.setClosable(true);
        this.setResizable(true);
        this.setIconifiable(true);
        this.setTitle("REGISTRAR NUEVO CLIENTE");
    }
    
    private void validar(){
        verificador =0;
        Cliente cliente = new Cliente();
        apellido = txtApellido.getText();
        if(verificador==0){
            validarCUI();
            if(verificador ==2){
                validarCamposVacios();
                if(verificador ==2){
                    validarDireccion();
                    if(verificador==2){
                        cliente.setCUI(txtCUI.getText());
                        cliente.setNombre(nombre);
                        if(verificador==2){
                           validarCelular();
                            if(verificador==2){
                                cliente.setTelefono(txtCelular.getText());
                                cliente.setDireccion(txtDireccion.getText());
                                validarNumeroNIT();
                                 if(verificador==2){
                                    cliente.setNIT(txtNIT.getText());
                                    if(cliente.GuardarCliente(IngresarUsuario.conector)){
                                        vaciarCampos();
                                        this.setVisible(false);
                                    } 
                                 }
                            }
                        }
                    }
                }
            }
        } 
    }
    
    public void validarCelular(){
        if(txtCelular.getText().length()!=8){
            verificador = 1;
            JOptionPane.showMessageDialog(null,"numero de celular INVALIDO");
        }else if(txtCelular.getText().length()==8){
             verificador = 2;
        }
    }
    
    public void validarNumeroNIT(){
        if(txtNIT.getText().length()!=9 || txtNIT.getText().isEmpty()){
            verificador = 1;
            JOptionPane.showMessageDialog(null,"numero de celular INVALIDO");
        }else if(txtNIT.getText().length()==9 && !txtNIT.getText().isEmpty()){
            
            verificador = 2;
        }
    }
        
   
    public void validarCamposVacios(){
        if(txtNombre.getText().isEmpty()){
            verificador =1;
            JOptionPane.showMessageDialog(null,"Nombre requerido");
        }
        if(!txtNombre.getText().isEmpty()){
            verificador =2;
        }
        if(verificador==2){
            if(txtApellido.getText().isEmpty()){
                verificador =1;
                JOptionPane.showMessageDialog(null,"Apellido requerido");
                System.out.println("vacio");
            } if(!txtApellido.getText().isEmpty()){
                nombre = txtNombre.getText() + " "+ txtApellido.getText();
                
                verificador = 2;
            }
        }else if(verificador ==2){
            if(txtCUI.getText().isEmpty()){
                verificador =1;
                JOptionPane.showMessageDialog(null,"Apellido requerido");
                System.out.println("vacio");
            }else if(!txtCUI.getText().isEmpty()){
                cui = txtCUI.getText();
                
                verificador =2;
            }
        } else if(verificador ==2){
            if(txtCelular.getText().isEmpty()){
                verificador =1;
                JOptionPane.showMessageDialog(null,"Apellido requerido");
                System.out.println("vacio");
            }else {
                verificador =2;
            }
        }
    }
    private void validarDireccion(){
        if(txtDireccion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"CUI requiere 13 digitos");
            verificador = 1;
        }if(!txtDireccion.getText().isEmpty()){
            verificador = 2;
        }
    }
    String cui;
     private void validarCUI(){	
            if (txtCUI.getText().length() !=13){
                JOptionPane.showMessageDialog(null,"CUI requiere 13 digitos");
                verificador =1;
            } else if (txtCUI.getText().length()==13){
                verificador =2;
                
            }
    }
     
     public void vaciarCampos(){
        txtNIT.setText("");
        txtCelular.setText("");
        txtApellido.setText("");
        txtNombre.setText("");
        txtCUI.setText("");
    }
     
    private void Diseño( int codigoRuta){
         System.out.println(codigoRuta);
        this.setClosable(true);
        this.setResizable(true);
        this.setIconifiable(true);
        this.setTitle("AGREGAR CLIENTE");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCUI;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCelular1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtCUI;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
