/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enviospractica1.UI.Administrador;

import enviospractica1.Backend.Destino;
import enviospractica1.Backend.PuntoControl;
import enviospractica1.ConectorMySQL;
import enviospractica1.UI.IngresarUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author astridmc
 */
public class ModificadorPrecio extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificadorPrecio
     */
    PuntoControl puntoControl = new PuntoControl();
    Destino destinos = new Destino();
    private int contador;
    private int aux=1;
    public ModificadorPrecio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblTitulo3 = new javax.swing.JLabel();
        modificado = new javax.swing.JComboBox<>();
        lblModificados = new javax.swing.JLabel();
        txtNuevoMonto = new javax.swing.JTextField();
        lblCodRuta2 = new javax.swing.JLabel();
        txtMontoActual = new javax.swing.JLabel();
        lblNuevoMonto = new javax.swing.JLabel();
        lblMontoActual = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        aModificar = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(141, 234, 179));

        LblTitulo3.setFont(new java.awt.Font("Abyssinica SIL", 1, 30)); // NOI18N
        LblTitulo3.setForeground(new java.awt.Color(30, 65, 32));
        LblTitulo3.setText("MODIFICAR PRECIO DE");

        modificado.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        modificado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "******" }));
        modificado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modificadoItemStateChanged(evt);
            }
        });
        modificado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificadoMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificadoMouseClicked(evt);
            }
        });
        modificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificadoActionPerformed(evt);
            }
        });

        lblModificados.setFont(new java.awt.Font("Abyssinica SIL", 1, 30)); // NOI18N
        lblModificados.setForeground(new java.awt.Color(30, 65, 32));
        lblModificados.setText("********************");

        txtNuevoMonto.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        txtNuevoMonto.setForeground(new java.awt.Color(13, 58, 12));
        txtNuevoMonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNuevoMontoMouseClicked(evt);
            }
        });
        txtNuevoMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoMontoActionPerformed(evt);
            }
        });
        txtNuevoMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNuevoMontoKeyTyped(evt);
            }
        });

        lblCodRuta2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblCodRuta2.setForeground(new java.awt.Color(30, 65, 32));
        lblCodRuta2.setText("Q.");

        txtMontoActual.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtMontoActual.setForeground(new java.awt.Color(30, 65, 32));
        txtMontoActual.setText("*******");

        lblNuevoMonto.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblNuevoMonto.setForeground(new java.awt.Color(30, 65, 32));
        lblNuevoMonto.setText("Nuevo Monto:");

        lblMontoActual.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblMontoActual.setForeground(new java.awt.Color(30, 65, 32));
        lblMontoActual.setText("Monto Actual            Q.");

        btnGuardar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        aModificar.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        aModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Global Ruta", "Individual Ruta ", "Destino" }));
        aModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aModificarMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aModificarMouseClicked(evt);
            }
        });
        aModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModificados)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblTitulo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aModificar, 0, 340, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblNuevoMonto)
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodRuta2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNuevoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(modificado, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtMontoActual)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(lblMontoActual)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTitulo3)
                    .addComponent(aModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(lblModificados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(txtMontoActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoMonto)
                    .addComponent(lblCodRuta2)
                    .addComponent(lblNuevoMonto))
                .addGap(34, 34, 34)
                .addComponent(btnGuardar)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(278, Short.MAX_VALUE)
                    .addComponent(lblMontoActual)
                    .addGap(180, 180, 180)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificadoMousePressed
        if(contador ==1){
            
            contador =2;
        }
    }//GEN-LAST:event_modificadoMousePressed

    private void modificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificadoActionPerformed
        
    }//GEN-LAST:event_modificadoActionPerformed

    private void txtNuevoMontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNuevoMontoMouseClicked

    }//GEN-LAST:event_txtNuevoMontoMouseClicked

    private void txtNuevoMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoMontoActionPerformed

    private void txtNuevoMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuevoMontoKeyTyped
        char a = evt.getKeyChar();
        if(a<'0'||a>'9') evt.consume();
        contador =1;
    }//GEN-LAST:event_txtNuevoMontoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(!txtNuevoMonto.getText().isEmpty()){
            cambiarPrecios(IngresarUsuario.conector);
            contador =1;
        }else{
            JOptionPane.showMessageDialog(null,"no ha especificado Monto");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void aModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aModificarMousePressed
        aux=1;
    }//GEN-LAST:event_aModificarMousePressed

    private void aModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aModificarActionPerformed

    private void modificadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificadoMouseClicked
        modificado.removeAllItems();
        obtenerAModificar(IngresarUsuario.conector);
    }//GEN-LAST:event_modificadoMouseClicked

    private void aModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aModificarMouseClicked
        modificado.removeAllItems();
        obtenerAModificar(IngresarUsuario.conector);
    }//GEN-LAST:event_aModificarMouseClicked

    private void modificadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modificadoItemStateChanged
        obtenerPreciosAModificar(IngresarUsuario.conector);
    }//GEN-LAST:event_modificadoItemStateChanged
    // obtiene el item seleccionado 
    private void obtenerAModificar(ConectorMySQL conector){
        if(aModificar.getSelectedIndex() ==0){ //precio Global de la ruta
            lblModificados.setText("Elija Punto De Control ");
            puntoControl.ListarPuntos(conector, modificado);
            puntoControl.obtenerPrecioGlobal(conector);
            lblMontoActual.setText("Monto Actual/ Hora   Q.");
        }else if(aModificar.getSelectedIndex()==1){ //precio Individual de la ruta
            lblModificados.setText("Elija Punto De Control ");
            lblMontoActual.setText("Monto Actual/ Hora   Q.");
            puntoControl.ListarPuntos(conector, modificado);
            puntoControl.obtenerPrecioGlobal(conector);
        }else if(aModificar.getSelectedIndex()==2){ // precio del destino
            lblModificados.setText("Elija el Destino ");
            lblMontoActual.setText("Monto Actual            Q.");
            destinos.ListarDestinos(conector, modificado);
            destinos.obtenerPrecio(conector, modificado.getSelectedItem().toString());
        }
    }
    
    private void obtenerPreciosAModificar(ConectorMySQL conector){
        if(aModificar.getSelectedIndex() ==0){ //precio Global de la ruta
            puntoControl.obtenerPrecioGlobal(conector);
            txtMontoActual.setText(String.valueOf(puntoControl.getPrecioGlobal()));
        }else if(aModificar.getSelectedIndex()==1){ //precio Individual de la ruta
            puntoControl.obtenerPrecioGlobal(conector);
            txtMontoActual.setText(String.valueOf(puntoControl.getPrecioIndividual()));
        }else if(aModificar.getSelectedIndex()==2){ // precio del destino
            try{
            if( modificado.getSelectedItem().toString() != null){
                destinos.obtenerPrecio(conector, modificado.getSelectedItem().toString());
                txtMontoActual.setText(String.valueOf(destinos.getMonto()));
            }
            } catch(java.lang.NullPointerException e){
            }
        }
    }
    private void vaciarCampos(){
        txtMontoActual.setText("***");
        txtNuevoMonto.setText("  ");
        lblModificados.setText("********************");
        modificado.removeAllItems();
    }

    private void cambiarPrecios(ConectorMySQL conector){
        if(aModificar.getSelectedIndex() ==0){ //precio Global de la ruta
            puntoControl.CambiarPrecioGlobal(conector, txtNuevoMonto, modificado);
            this.setVisible(false);
            vaciarCampos();
        }else if(aModificar.getSelectedIndex()==1){ //precio Individual de la ruta
            puntoControl.CambiarPrecioIndividual(conector, txtNuevoMonto, modificado);
            this.setVisible(false);
            vaciarCampos();
        }else if(aModificar.getSelectedIndex()==2){ // precio del destino
            try{
                if( modificado.getSelectedItem().toString() != null){
                    destinos.CambiarPrecio(conector, txtNuevoMonto, modificado);
                    this.setVisible(false);
                    vaciarCampos();
                }
            } catch(java.lang.NullPointerException e){
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTitulo3;
    private javax.swing.JComboBox<String> aModificar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodRuta2;
    private javax.swing.JLabel lblModificados;
    private javax.swing.JLabel lblMontoActual;
    private javax.swing.JLabel lblNuevoMonto;
    private javax.swing.JComboBox<String> modificado;
    private javax.swing.JLabel txtMontoActual;
    private javax.swing.JTextField txtNuevoMonto;
    // End of variables declaration//GEN-END:variables
}
