/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enviospractica1.UI.Administrador;

import javax.swing.JOptionPane;

/**
 *
 * @author astridmc
 */
public class NuevoUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoUsuario
     */
    public NuevoUsuario() {
        initComponents();
        Diseño();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCUI = new javax.swing.JTextField();
        lblCUI1 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblCelular2 = new javax.swing.JLabel();
        rangos = new javax.swing.JComboBox<>();
        LblTitulo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblConfirmarContraseña = new javax.swing.JLabel();
        contraseña1 = new javax.swing.JPasswordField();
        contraseña = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        lblCelular3 = new javax.swing.JLabel();
        panelAsignar = new javax.swing.JPanel();
        lblCelular1 = new javax.swing.JLabel();
        Rutas = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(141, 234, 179));

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(30, 65, 32));
        lblNombre.setText("Ingrese Nombres :");

        lblApellido.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(30, 65, 32));
        lblApellido.setText("Ingrese Apellidos :");

        txtApellido.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(13, 58, 12));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(13, 58, 12));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtCUI.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtCUI.setForeground(new java.awt.Color(13, 58, 12));
        txtCUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCUIActionPerformed(evt);
            }
        });
        txtCUI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCUIKeyTyped(evt);
            }
        });

        lblCUI1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblCUI1.setForeground(new java.awt.Color(30, 65, 32));
        lblCUI1.setText("Ingrese Numero de CUI:");

        txtCelular.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(13, 58, 12));
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });

        lblCelular2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblCelular2.setForeground(new java.awt.Color(30, 65, 32));
        lblCelular2.setText("Rango: ");

        rangos.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        rangos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rango", "Administrador", "Operador", "Recepcionista", " " }));

        LblTitulo.setFont(new java.awt.Font("Abyssinica SIL", 1, 28)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(30, 65, 32));
        LblTitulo.setText("REGISTRO DE UN NUEVO USUARIO");

        lblContraseña.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(30, 65, 32));
        lblContraseña.setText("Contraseña:");

        lblConfirmarContraseña.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblConfirmarContraseña.setForeground(new java.awt.Color(30, 65, 32));
        lblConfirmarContraseña.setText("Confirme Contraseña:");

        contraseña1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        contraseña1.setText("jPasswordField1");
        contraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contraseña1MouseClicked(evt);
            }
        });
        contraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseña1ActionPerformed(evt);
            }
        });

        contraseña.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        contraseña.setText("jPasswordField1");
        contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contraseñaMouseClicked(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnGuardar.setText("REGISTRAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblCelular3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblCelular3.setForeground(new java.awt.Color(30, 65, 32));
        lblCelular3.setText("Ingrese Numero de Celular:");

        panelAsignar.setBackground(new java.awt.Color(141, 234, 179));

        lblCelular1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblCelular1.setForeground(new java.awt.Color(30, 65, 32));
        lblCelular1.setText("Asignar punto De Control :");

        Rutas.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        Rutas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rango", "Administrador", "Operador", "Recepcionista", " " }));
        Rutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAsignarLayout = new javax.swing.GroupLayout(panelAsignar);
        panelAsignar.setLayout(panelAsignarLayout);
        panelAsignarLayout.setHorizontalGroup(
            panelAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelAsignarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCelular1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsignarLayout.createSequentialGroup()
                        .addComponent(Rutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelAsignarLayout.setVerticalGroup(
            panelAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignarLayout.createSequentialGroup()
                .addComponent(lblCelular1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(LblTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellido)
                            .addComponent(lblNombre)
                            .addComponent(lblCUI1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCUI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContraseña)
                                    .addComponent(lblConfirmarContraseña))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCelular2)
                                .addGap(26, 26, 26)
                                .addComponent(rangos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGap(107, 107, 107))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(lblCelular3)
                    .addContainerGap(444, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitulo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblNombre)
                        .addGap(23, 23, 23)
                        .addComponent(lblApellido)
                        .addGap(34, 34, 34)
                        .addComponent(lblCUI1)
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rangos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCelular2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblContraseña)
                            .addComponent(contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConfirmarContraseña)
                            .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(258, Short.MAX_VALUE)
                    .addComponent(lblCelular3)
                    .addGap(218, 218, 218)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a'|| c>'z') && (c<'A'||c>'z')&&(c<' '|| c>' ')) {
            evt.consume();}
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCUIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCUIActionPerformed

    private void txtCUIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCUIKeyTyped
        char b = evt.getKeyChar();
        if(b<'0'||b>'9') evt.consume();
        if(txtCUI.getText().length()==13) evt.consume();
    }//GEN-LAST:event_txtCUIKeyTyped

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        char a = evt.getKeyChar();
        if(a<'0'||a>'9') evt.consume();
        if(txtCelular.getText().length()==8) evt.consume();
    }//GEN-LAST:event_txtCelularKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        validarCampos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void contraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseña1ActionPerformed

    private void contraseña1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseña1MouseClicked
        contraseña1.setText("");
    }//GEN-LAST:event_contraseña1MouseClicked

    private void contraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaMouseClicked
        contraseña.setText("");
    }//GEN-LAST:event_contraseñaMouseClicked

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
         char c = evt.getKeyChar();
        if ((c<'a'|| c>'z') && (c<'A'||c>'z')&&(c<' '|| c>' ')) {
            evt.consume();}
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void RutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutasActionPerformed
        if(Rutas.getSelectedIndex()==2){
            panelAsignar.setVisible(true);
        }
    }//GEN-LAST:event_RutasActionPerformed

    private int validador;
    
    public void validarCampos(){
        validador =0;
        if(txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty()){
            validador =0;
            JOptionPane.showMessageDialog(null,"Campo obligatorio vacio");
        }else{
            validador =2;
            if(txtCUI.getText().isEmpty()|| txtCelular.getText().isEmpty()){
                validador=0;
                JOptionPane.showMessageDialog(null,"Campo obligatorio vacio");
            } else{
                validador =2;
            }
        }
        if(validador ==2){
            validarContraseñas();
            if(validador ==2){
                validarCUI();
                if(validador == 2){
                    validarCelular();
                    if(validador ==2){
                        validarRango();
                        if(validador==2){
                            JOptionPane.showMessageDialog(null,"El usuario "+ txtNombre.getText() + "se ha Registrado con exito");
                            VaciarCampos();
                            this.setVisible(false);
                        }
                    }
                }
            }
        }
    }
    
    public void validarRango(){
        if(rangos.getSelectedIndex()==0){
            validador=1;
            JOptionPane.showMessageDialog(null,"no ha especificado algun rango");
        }else {
            validador=2;
        }
    }
    
    public void validarCUI(){
        if(txtCUI.getText().length()!=13){
            JOptionPane.showMessageDialog(null,"CUI requiere 13 digitos");
            validador=1;
        } if(txtCUI.getText().length()==13){
            validador =2;
        }
    }
    
    public void validarCelular(){
        if(txtCelular.getText().length()!=8){
            JOptionPane.showMessageDialog(null,"CUI requiere 13 digitos");
            validador=1;
        } if(txtCelular.getText().length()==9){
            validador =2;
        }
    }
    
    private void validarContraseñas(){
        int puntero =0;
        if (contraseña.getPassword().length!= contraseña1.getPassword().length){ 
            validador =1;
            JOptionPane.showMessageDialog(null,"Las contraseñas no conciden");
        } 
        else{ 
            while((validador !=1)&&(puntero < contraseña.getPassword().length)){ 
            if (contraseña.getPassword()[puntero] != contraseña1.getPassword()[puntero]){ 
                validador = 1; 
                JOptionPane.showMessageDialog(null,"Las contraseñas no conciden");
            } 
            puntero++; 
            validador=2;
            } 
        } 
    }
    
     private void Diseño(){
        this.setClosable(true);
        this.setResizable(true);
        this.setIconifiable(true);
        this.setTitle("AGREGAR USUSARIO");
        panelAsignar.setVisible(false);
    }

    private void VaciarCampos(){
        txtApellido.setText("");
        txtCUI.setText("");
        txtNombre.setText("");
        txtCelular.setText("");
        rangos.setSelectedIndex(0);
        contraseña.setText("             ");
        contraseña1.setText("         .   ");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JComboBox<String> Rutas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JPasswordField contraseña1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCUI1;
    private javax.swing.JLabel lblCelular1;
    private javax.swing.JLabel lblCelular2;
    private javax.swing.JLabel lblCelular3;
    private javax.swing.JLabel lblConfirmarContraseña;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panelAsignar;
    private javax.swing.JComboBox<String> rangos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCUI;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
