
package enviospractica1.UI.Administrador;

import enviospractica1.Backend.Destino;
import enviospractica1.Backend.Ruta;
import enviospractica1.ConectorMySQL;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import enviospractica1.UI.IngresarUsuario;
import java.util.logging.Level;
import java.util.logging.Logger;

    /**
     *
     * @author astridmc
     */
public class NuevaRuta extends javax.swing.JInternalFrame {
        
    /**
     * Creates new form NuevaRuta
     */
    private int contador =1;
    private int codDestino;
    private int numeroCodRuta;
    Destino destinos = new Destino();
    Ruta ruta = new Ruta();
    
    public NuevaRuta(int CodRuta) {
        initComponents();
            Diseño(CodRuta);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        txtCodRuta = new javax.swing.JLabel();
        lblCodRuta = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JButton();
        destino = new javax.swing.JComboBox<>();
        verRutas = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(141, 234, 179));

        LblTitulo.setFont(new java.awt.Font("Abyssinica SIL", 1, 42)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(30, 65, 32));
        LblTitulo.setText("AGREGAR NUEVA RUTA");

        txtCodRuta.setFont(new java.awt.Font("Abyssinica SIL", 1, 28)); // NOI18N
        txtCodRuta.setForeground(new java.awt.Color(1, 101, 168));
        txtCodRuta.setText("*********");

        lblCodRuta.setFont(new java.awt.Font("Abyssinica SIL", 1, 28)); // NOI18N
        lblCodRuta.setForeground(new java.awt.Color(30, 65, 32));
        lblCodRuta.setText("CODIGO DE LA RUTA:");

        lblDestino.setFont(new java.awt.Font("Abyssinica SIL", 1, 28)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(30, 65, 32));
        lblDestino.setText("Destino:");

        btnGuardar1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnGuardar1.setText("GUARDAR");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        destino.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "******" }));
        destino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destinoMouseClicked(evt);
            }
        });
        destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoActionPerformed(evt);
            }
        });

        verRutas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        verRutas.setText("VER RUTAS EXISTENETES");
        verRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(verRutas)
                        .addGap(31, 31, 31))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(LblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodRuta)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodRuta))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDestino)
                                .addGap(193, 193, 193)
                                .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitulo)
                .addGap(18, 18, 18)
                .addComponent(verRutas)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodRuta)
                    .addComponent(lblCodRuta))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDestino)
                    .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnGuardar1)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        if(ruta.GuardarRutal(IngresarUsuario.conector, destino, numeroCodRuta)){
            JOptionPane.showMessageDialog(null,"La Ruta se Ha creado con exito");
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"ha fallado la conexion a la base de datos");
        }
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoActionPerformed
    private int numero =1;
    private void destinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destinoMouseClicked
        if(numero ==1){
            destinos.ListarDestinos(IngresarUsuario.conector, destino);
            numero =2;
        }
    }//GEN-LAST:event_destinoMouseClicked

    private void verRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRutasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verRutasActionPerformed
 
    
     private void Diseño( int codigoRuta){
         System.out.println(codigoRuta);
        this.setClosable(true);
        this.setResizable(true);
        this.setIconifiable(true);
        this.setTitle("NUEVA RUTA");
        txtCodRuta.setText("A"+String.valueOf(codigoRuta));
        numero =1;
        numeroCodRuta = codigoRuta;
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JComboBox<String> destino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodRuta;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel txtCodRuta;
    private javax.swing.JButton verRutas;
    // End of variables declaration//GEN-END:variables
}
