/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enviospractica1.UI.Administrador;

import enviospractica1.Backend.PuntoControl;
import enviospractica1.Backend.Ruta;
import enviospractica1.Backend.Usuario;
import enviospractica1.UI.IngresarUsuario;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author astridmc
 */
public class Reportes extends javax.swing.JInternalFrame {

    PuntoControl puntoControl = new PuntoControl();
    Usuario usuario = new Usuario();
    Ruta rutas = new Ruta();
    int reconocedor= 0;
    /**
     * Creates new form Reportes
     * @param reconocedor
     */
    public Reportes(int reconocedor) {
        initComponents();
        this.reconocedor = reconocedor;
        nombrarColumnas();
        Diseño();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportes = new javax.swing.JTable();
        panelFechas = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblTitulo2 = new javax.swing.JLabel();
        dateChooserDel = new datechooser.beans.DateChooserCombo();
        dateChooserAl = new datechooser.beans.DateChooserCombo();
        jButton1 = new javax.swing.JButton();
        activas = new javax.swing.JRadioButton();
        activas1 = new javax.swing.JRadioButton();
        LblTitulo1 = new javax.swing.JLabel();
        lblNombreReporte = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(169, 244, 219));

        tablaReportes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tablaReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "campo 1", "campo 2", "campo 3", "campo 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaReportesMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tablaReportes);
        if (tablaReportes.getColumnModel().getColumnCount() > 0) {
            tablaReportes.getColumnModel().getColumn(0).setHeaderValue("campo 1");
            tablaReportes.getColumnModel().getColumn(1).setHeaderValue("campo 2");
            tablaReportes.getColumnModel().getColumn(2).setHeaderValue("campo 3");
            tablaReportes.getColumnModel().getColumn(3).setHeaderValue("campo 4");
        }

        panelFechas.setBackground(new java.awt.Color(169, 244, 219));
        panelFechas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 178, 255), 3));

        LblTitulo.setFont(new java.awt.Font("Abyssinica SIL", 1, 28)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(30, 65, 32));
        LblTitulo.setText("AL:");

        LblTitulo2.setFont(new java.awt.Font("Abyssinica SIL", 1, 28)); // NOI18N
        LblTitulo2.setForeground(new java.awt.Color(30, 65, 32));
        LblTitulo2.setText("DEL:");

        jButton1.setText("BUSCAR");

        activas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        activas.setText("Solo Inactivas");
        activas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activasActionPerformed(evt);
            }
        });

        activas1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        activas1.setText("Solo Activas");

        javax.swing.GroupLayout panelFechasLayout = new javax.swing.GroupLayout(panelFechas);
        panelFechas.setLayout(panelFechasLayout);
        panelFechasLayout.setHorizontalGroup(
            panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFechasLayout.createSequentialGroup()
                        .addComponent(LblTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(dateChooserDel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(LblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(dateChooserAl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(panelFechasLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activas1)
                        .addGap(29, 29, 29)
                        .addComponent(activas)
                        .addGap(49, 49, 49))))
        );
        panelFechasLayout.setVerticalGroup(
            panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechasLayout.createSequentialGroup()
                .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblTitulo2)
                    .addComponent(dateChooserAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panelFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(activas)
                    .addComponent(activas1))
                .addContainerGap())
        );

        LblTitulo1.setFont(new java.awt.Font("Abyssinica SIL", 1, 28)); // NOI18N
        LblTitulo1.setForeground(new java.awt.Color(30, 65, 32));
        LblTitulo1.setText("Reportes de");

        lblNombreReporte.setFont(new java.awt.Font("Abyssinica SIL", 1, 28)); // NOI18N
        lblNombreReporte.setForeground(new java.awt.Color(30, 65, 32));
        lblNombreReporte.setText("*****");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(LblTitulo1)
                .addGap(42, 42, 42)
                .addComponent(lblNombreReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTitulo1)
                    .addComponent(lblNombreReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addGap(109, 109, 109))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaReportesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaReportesMouseEntered

    private void activasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activasActionPerformed

    public void nombrarColumnas(){
         if (reconocedor ==1) {
            panelFechas.setVisible(false);
            lblNombreReporte.setText("RUTAS");
            centrar_datos();
            rutas.leerRuta(IngresarUsuario.conector, tablaReportes);
        } else if(reconocedor ==2){
            panelFechas.setVisible(false);
            lblNombreReporte.setText("CLIENTES");
            tablaReportes.getColumnModel().getColumn(0).setHeaderValue("Nombre                     ");
            tablaReportes.getColumnModel().getColumn(1).setHeaderValue("    NIT    ");
            tablaReportes.getColumnModel().getColumn(2).setHeaderValue("      CUI     ");
            tablaReportes.getColumnModel().getColumn(3).setHeaderValue(" Celular ");
        } else if(reconocedor ==3){
            lblNombreReporte.setText("GANANCIAS");
            panelFechas.setVisible(true);
            tablaReportes.getColumnModel().getColumn(0).setHeaderValue(" Cod. Ruta ");
            tablaReportes.getColumnModel().getColumn(1).setHeaderValue(" Ingreso  ");
            tablaReportes.getColumnModel().getColumn(2).setHeaderValue("  Costos  ");
            tablaReportes.getColumnModel().getColumn(3).setHeaderValue(" GANANCIAS ");
        }else if(reconocedor ==4){
            lblNombreReporte.setText("Rutas Populares");
            panelFechas.setVisible(true);
            tablaReportes.getColumnModel().getColumn(0).setHeaderValue("Cod. Ruta   ");
            tablaReportes.getColumnModel().getColumn(1).setHeaderValue("No.Puntos de Control");
            tablaReportes.getColumnModel().getColumn(2).setHeaderValue(" Cantidad de Paquetes ");
            tablaReportes.getColumnModel().getColumn(3).setHeaderValue(" Destino ");
        }else if(reconocedor ==5){
            lblNombreReporte.setText("Puntos De Control");
            panelFechas.setVisible(false);
            centrar_datos();
            puntoControl.leerPuntosDeControl(IngresarUsuario.conector, tablaReportes);
        }else if(reconocedor== 6){
            lblNombreReporte.setText("USUARIOS");
            panelFechas.setVisible(false);
            centrar_datos();
            usuario.leerUsuarios(IngresarUsuario.conector, tablaReportes);
        }
    }
    public void centrar_datos(){
           DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
            modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
            tablaReportes.getColumnModel().getColumn(0).setCellRenderer(modelocentrar);
            tablaReportes.getColumnModel().getColumn(1).setCellRenderer(modelocentrar); 
            tablaReportes.getColumnModel().getColumn(2).setCellRenderer(modelocentrar); 
            tablaReportes.getColumnModel().getColumn(3).setCellRenderer(modelocentrar); 
        }
    
    public void Diseño() {
        centrar_datos();
        this.setClosable(true);
        this.setResizable(true);
        this.setIconifiable(true);
        this.setTitle("REPORTES");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTitulo1;
    private javax.swing.JLabel LblTitulo2;
    private javax.swing.JRadioButton activas;
    private javax.swing.JRadioButton activas1;
    private datechooser.beans.DateChooserCombo dateChooserAl;
    private datechooser.beans.DateChooserCombo dateChooserDel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNombreReporte;
    private javax.swing.JPanel panelFechas;
    private javax.swing.JTable tablaReportes;
    // End of variables declaration//GEN-END:variables
}
