/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enviospractica1.UI;

import enviospractica1.Backend.Cliente;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author astridmc
 */
public class VerClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form verClientes
     */
    Cliente cliente = new Cliente();
    public VerClientes() {
        initComponents();
        Diseño();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();

        panelFondo.setBackground(new java.awt.Color(141, 234, 179));

        LblTitulo.setFont(new java.awt.Font("Abyssinica SIL", 1, 42)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(30, 65, 32));
        LblTitulo.setText("LISTADO DE CLIENTES");

        tablaClientes.setBackground(new java.awt.Color(197, 248, 241));
        tablaClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaClientes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "campo 1", "campo 2", "campo 3", "campo 4", "Direccion", "Paquetes En Ruta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.setAlignmentY(0.9F);
        tablaClientes.setRowHeight(25);
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaClientesMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);
        if (tablaClientes.getColumnModel().getColumnCount() > 0) {
            tablaClientes.getColumnModel().getColumn(0).setPreferredWidth(70);
            tablaClientes.getColumnModel().getColumn(1).setPreferredWidth(70);
            tablaClientes.getColumnModel().getColumn(2).setPreferredWidth(50);
            tablaClientes.getColumnModel().getColumn(3).setPreferredWidth(60);
            tablaClientes.getColumnModel().getColumn(4).setPreferredWidth(50);
            tablaClientes.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(LblTitulo)
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFondoLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                    .addGap(7, 7, 7)))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LblTitulo)
                .addContainerGap(433, Short.MAX_VALUE))
            .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFondoLayout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaClientesMouseEntered

    public void centrar_datos(){
           DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
            modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
            tablaClientes.getColumnModel().getColumn(0).setCellRenderer(modelocentrar);
            tablaClientes.getColumnModel().getColumn(1).setCellRenderer(modelocentrar); 
            tablaClientes.getColumnModel().getColumn(2).setCellRenderer(modelocentrar); 
            tablaClientes.getColumnModel().getColumn(3).setCellRenderer(modelocentrar); 
            tablaClientes.getColumnModel().getColumn(4).setCellRenderer(modelocentrar); 
        }
    private void Diseño(){
        centrar_datos();
        cliente.leerClientes(IngresarUsuario.conector, tablaClientes);
        this.setClosable(true);
        this.setResizable(true);
        this.setIconifiable(true);
        this.setTitle("LISTADO CLIENTES");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
